export const LOADING = 'LOADING';

export const TOKEN_DELETED = 'TOKEN_DELETED';
export const TOKEN_RECEIVED = 'TOKEN_RECEIVED';
export const TOKEN_NOT_RECEIVED = 'TOKEN_NOT_RECEIVED';

export const TOYS_RECEIVED = 'TOYS_RECEIVED';
export const TOYS_NOT_RECEIVED = 'TOYS_NOT_RECEIVED';
export const TOY_RECEIVED = 'TOY_RECEIVED';
export const TOY_NOT_RECEIVED = 'TOY_NOT_RECEIVED';

export const TRANSACTIONS_RECEIVED = 'TRANSACTIONS_RECEIVED';
export const TRANSACTIONS_NOT_RECEIVED = 'TRANSACTIONS_NOT_RECEIVED';
export const TRANSACTION_RECEIVED = 'TRANSACTION_RECEIVED';
export const TRANSACTION_NOT_RECEIVED = 'TRANSACTION_NOT_RECEIVED';

export const CATEGORIES_RECEIVED = 'CATEGORIES_RECEIVED';
export const CATEGORIES_NOT_RECEIVED = 'CATEGORIES_NOT_RECEIVED';
export const CATEGORY_RECEIVED = 'CATEGORY_RECEIVED';
export const CATEGORY_NOT_RECEIVED = 'CATEGORY_NOT_RECEIVED';